name: agrihive
description: "A smart agricultural management app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # HTTP & Networking
  http: ^1.3.0
  connectivity_plus: ^6.1.3  

  # Firebase Services
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # AI & Chatbot
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21  

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5  

  # Geolocation & Permissions
  geolocator: ^13.0.3  
  permission_handler: ^11.0.1  

  # Image Handling
  image_picker: ^1.1.2  

  # Environment Variables
  flutter_dotenv: ^5.1.0  
  shared_preferences: ^2.5.2
  google_generative_ai: ^0.4.6

  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"  # Path to your icon
  adaptive_icon_foreground: "assets/images/app_icon.png"  # For adaptive Android icons
  adaptive_icon_background: "#FFFFFF"  # Background color for Android

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/app_icon.png
    - assets/images/background.jpg
    - assets/images/Background2.jpg
    - assets/images/path1.png
    - assets/images/rice.jpg